### ISSUE TITLE
new pypi release?

### ISSUE THREAD

**Issue by Kentaczi** [mlflow/mlflow-export-import#184]
Hello,
I noticed that there have been several updates that are quite usefull like direct copy. Is it possible that you give us new version on pypi?
Best regards 😃

**Comment by mikeweltevrede** [comment]
Disclaimer: I am not the author nor a maintainer.

Notice in the README under [Setup > 5. Install from PyPI](https://github.com/mlflow/mlflow-export-import?tab=readme-ov-file#5-install-from-pypi) it is mentioned that "Legacy. Due to the quick turnaround time for bug ad feature fixes, this is deprecated." Some alternatives are mentioned there. Good luck :)
